/**
 * Dependency-free Sentry capture for the Cloudflare Worker (SSR) side.
 *
 * We deliberately DO NOT use @sentry/cloudflare or @sentry/astro: both want to
 * wrap the Worker's fetch handler, but the handler is generated by the pinned
 * @astrojs/cloudflare adapter (see CLAUDE.md — do not bump Astro 5 / adapter 12).
 * Wrapping the generated `_worker.js` is brittle. Instead this module speaks the
 * Sentry "envelope" ingestion protocol directly over `fetch`, which is all a
 * Worker needs and adds zero dependencies / zero bundle weight.
 *
 * The browser side is handled separately by the Sentry JS Loader in
 * `src/components/Analytics.astro`. This file is SERVER-ONLY.
 *
 * DSN comes from `env.SENTRY_DSN` (a wrangler var / secret) so error reporting
 * never depends on D1 — the database may be the very thing that is failing.
 */

interface ParsedDsn {
  envelopeUrl: string;
  publicKey: string;
  host: string;
  projectId: string;
}

/** Parse a Sentry DSN (`https://<key>@<host>/<projectId>`) into its parts. */
export function parseDsn(dsn: string): ParsedDsn | null {
  try {
    const u = new URL(dsn);
    const projectId = u.pathname.replace(/^\//, "");
    if (!u.username || !projectId) return null;
    return {
      publicKey: u.username,
      host: u.host,
      projectId,
      envelopeUrl: `${u.protocol}//${u.host}/api/${projectId}/envelope/?sentry_key=${u.username}&sentry_version=7`,
    };
  } catch {
    return null;
  }
}

/** Best-effort parse of a V8/Spidermonkey-style Error.stack into Sentry frames. */
function stackFrames(stack: string | undefined): { filename?: string; function?: string; lineno?: number; colno?: number }[] {
  if (!stack) return [];
  const frames: { filename?: string; function?: string; lineno?: number; colno?: number }[] = [];
  for (const raw of stack.split("\n")) {
    const line = raw.trim();
    // "at fn (url:line:col)" | "at url:line:col"
    const m = line.match(/^at\s+(?:(.*?)\s+\()?(.*?):(\d+):(\d+)\)?$/);
    if (!m) continue;
    frames.push({
      function: m[1] || "?",
      filename: m[2],
      lineno: Number(m[3]),
      colno: Number(m[4]),
    });
  }
  // Sentry expects frames oldest-first; stacks are newest-first.
  return frames.reverse();
}

export interface CaptureContext {
  request?: Request;
  level?: "fatal" | "error" | "warning" | "info";
  tags?: Record<string, string>;
  extra?: Record<string, unknown>;
  transaction?: string;
}

function buildEvent(env: Env, err: unknown, ctx: CaptureContext) {
  const error = err instanceof Error ? err : new Error(typeof err === "string" ? err : "Unknown server error");
  // Sentry requires a 32-hex-char event_id. Both branches yield exactly that:
  // randomUUID (always present in Workers) stripped of dashes, or 16 random bytes.
  const eventId = (
    crypto.randomUUID?.() ??
    Array.from(crypto.getRandomValues(new Uint8Array(16)), (b) => b.toString(16).padStart(2, "0")).join("")
  ).replace(/-/g, "");
  const url = ctx.request ? new URL(ctx.request.url) : null;

  return {
    eventId,
    payload: {
      event_id: eventId,
      timestamp: Date.now() / 1000,
      platform: "node",
      level: ctx.level ?? "error",
      logger: "worker",
      server_name: "cloudflare-worker",
      environment: env.SENTRY_ENVIRONMENT || (import.meta.env.DEV ? "development" : "production"),
      release: env.SENTRY_RELEASE || undefined,
      transaction: ctx.transaction ?? (url ? url.pathname : undefined),
      exception: {
        values: [
          {
            type: error.name || "Error",
            value: error.message || String(err),
            stacktrace: { frames: stackFrames(error.stack) },
            mechanism: { type: "generic", handled: false },
          },
        ],
      },
      request: ctx.request
        ? {
            url: ctx.request.url,
            method: ctx.request.method,
            headers: {
              "User-Agent": ctx.request.headers.get("user-agent") || "",
              Referer: ctx.request.headers.get("referer") || "",
            },
          }
        : undefined,
      tags: { runtime: "cloudflare-workers", ...(ctx.tags ?? {}) },
      extra: ctx.extra,
    },
  };
}

/**
 * Send an exception to Sentry. Fire-and-forget: never throws, returns the
 * in-flight promise so callers can hand it to `ctx.waitUntil(...)`. No-ops
 * (resolves immediately) when no DSN is configured.
 */
export function captureServerException(env: Env, err: unknown, ctx: CaptureContext = {}): Promise<void> {
  const dsn = env.SENTRY_DSN;
  if (!dsn) return Promise.resolve();
  const parsed = parseDsn(dsn);
  if (!parsed) return Promise.resolve();

  const { eventId, payload } = buildEvent(env, err, ctx);
  const header = JSON.stringify({ event_id: eventId, sent_at: new Date().toISOString(), dsn });
  const itemHeader = JSON.stringify({ type: "event" });
  const body = `${header}\n${itemHeader}\n${JSON.stringify(payload)}`;

  return fetch(parsed.envelopeUrl, {
    method: "POST",
    headers: { "Content-Type": "application/x-sentry-envelope" },
    body,
  })
    .then(() => undefined)
    .catch(() => undefined);
}
