// generated by scripts/gen-turkey.mjs — Türkiye il merkezleri (public/turkey.svg uzayı)
export const TURKEY_VIEWBOX = "-8 -8 716 312";
export const CITY_XY: Record<string, [number, number]> = {"İstanbul":[119.3,48.4],"Kocaeli":[151,62.2],"Tekirdağ":[64,49.7],"Kırklareli":[70.4,17.9],"Çanakkale":[32.5,90.4],"Bursa":[123.2,93.7],"Sakarya":[171.7,69],"Düzce":[201.3,61.2],"Zonguldak":[222.2,44.4],"Ankara":[243.8,114.5],"İzmir":[47,164.6],"Antalya":[181.5,256.6],"Kayseri":[365.9,167.5],"Hatay":[382.7,266.6]};
