#!/usr/bin/env python3
"""Merge speaker-enrichment workflow output into UPDATE statements.
Input:  scratchpad/enrich.json  ({results:[{slug,title,bio,linkedin,github,twitter,website,photo_url,confidence}]})
Output: scripts/speaker-enrich.sql  (UPDATE speakers SET ... only for non-empty fields)
"""
import json, sys
SC = sys.argv[1]; ROOT = sys.argv[2]
data = json.load(open(f"{SC}/enrich.json"))
res = data.get("results", data) if isinstance(data, dict) else data

def q(v): return "'" + str(v).replace("'", "''") + "'"
def clean(v):
    if not v: return None
    v = str(v).strip()
    return v or None

lines = ["-- Generated by apply-speaker-enrich.py — speaker profile enrichment.\n"]
n_title = n_bio = n_social = n_photo = 0
for r in res:
    slug = r.get("slug")
    if not slug or (r.get("confidence") == "none"):
        # still allow socials/photo if present even when conf none? skip wholesale.
        pass
    sets = []
    title = clean(r.get("title"))
    bio = clean(r.get("bio"))
    photo = clean(r.get("photo_url"))
    socials = {}
    for k in ("linkedin", "github", "twitter", "website", "instagram"):
        val = clean(r.get(k))
        if val: socials[k] = val
    if title: sets.append(f"title={q(title)}"); n_title += 1
    if bio: sets.append(f"bio={q(bio)}"); n_bio += 1
    if photo and "avatars.githubusercontent.com" in photo:
        sets.append(f"avatar_url={q(photo)}"); n_photo += 1
    if socials:
        sets.append(f"socials={q(json.dumps(socials, ensure_ascii=False))}"); n_social += 1
    if not sets: continue
    lines.append(f"UPDATE speakers SET {', '.join(sets)}, updated_at=unixepoch() WHERE slug={q(slug)};")

open(f"{ROOT}/scripts/speaker-enrich.sql", "w").write("\n".join(lines) + "\n")
print(f"updates: {len([l for l in lines if l.startswith('UPDATE')])}")
print(f"  titles={n_title} bios={n_bio} socials={n_social} photos={n_photo}")
