-- GENERATED from scripts/gathin-events.json (Gathin community events). Do not edit by hand.
-- Regenerate: node scripts/gen-events.mjs > scripts/events.sql
DELETE FROM events;
INSERT OR REPLACE INTO events (id, slug, title, summary, description, cover_image, community, category, location, city, is_online, starts_at, ends_at, registration_url, source, status, is_featured, tags, sort_order) VALUES
  ('gathin-10019836122315806087', 'jetpack-compose-accessibility-networking', 'Jetpack Compose & Accessibility + Networking', 'Aylar boyunca birlikte öğrenen, gelişen ve deneyimlerini paylaşan geliştiricileri bu kez ekranların arkasından çıkarıp aynı ortamda buluşturuyoruz. Serinin…', '<p>Aylar boyunca birlikte öğrenen, gelişen ve deneyimlerini paylaşan geliştiricileri bu kez ekranların arkasından çıkarıp aynı ortamda buluşturuyoruz.<br><br>Serinin üçüncü ve son oturumunda teknik içerik kadar topluluk olmanın gücüne de odaklanacağız. Yazılım dünyasında yeni fırsatların, iş birliklerinin ve dostlukların çoğu zaman bir kahve molasında başlayan sohbetlerle ortaya çıktığını biliyoruz. Bu nedenle bu buluşma; yalnızca bilgi paylaşımı değil, aynı zamanda güçlü bağlantılar kurabileceğiniz özel bir networking deneyimi sunacak.<br><br>Bu yüz yüze etkinlikte sektör profesyonelleri, eğitmenler, mentorlar ve bootcamp katılımcıları bir araya gelerek deneyimlerini paylaşacak; Android ekosistemindeki güncel gelişmeleri, kariyer yolculuklarını ve gerçek proje deneyimlerini samimi bir ortamda konuşma fırsatı bulacak.<br><br><strong><em>💭 Etkinlikte Sizleri Neler Bekliyor?</em></strong><br><br>📌 Android geliştiricileriyle birebir tanışma ve networking fırsatı.<br>📌 Eğitmenler ve sektör profesyonelleriyle soru-cevap oturumları.<br>📌 Kariyer yolculukları ve gerçek proje deneyimlerine dair samimi sohbetler.<br>📌 Android ekosistemindeki güncel trendler ve gelecek teknolojiler üzerine paylaşımlar.<br>📌 Yeni ekip arkadaşları, çalışma arkadaşları ve potansiyel iş birlikleriyle tanışma fırsatı.<br>📌 Bootcamp sürecinin değerlendirilmesi ve katılımcı deneyimlerinin paylaşılması.<br>📌 Topluluğun bir parçası olarak ilham veren hikâyeler dinleme ve kendi hikâyenizi paylaşma imkânı.<br><br><strong><em>🎯 Kimler Katılmalı?</em></strong><br><br>🔷 Bootcamp süresince birlikte öğrenen katılımcılar.<br>🔷 Android ekosistemindeki profesyonellerle tanışmak isteyen geliştiriciler.<br>🔷 Kariyerine yön vermek, deneyim paylaşımında bulunmak ve yeni bağlantılar kurmak isteyen yazılım mühendisleri.<br>🔷 Topluluk kültürünün bir parçası olmak ve birlikte üretmenin gücünü deneyimlemek isteyen herkes.<br><br>Bazen en değerli kazanımlar bir kod satırından değil, doğru insanlarla aynı masayı paylaşmaktan doğar. Yeni fikirler, yeni dostluklar ve ilham veren sohbetlerle bu yolculuğu birlikte tamamlamak için sizleri üçüncü ve son oturumumuza bekliyoruz.<br><br>– MultiGroup ❤️ Wite</p>', 'https://files-01.apiollon.com/download.php?file=6a32717d680d85.02507357.jpg&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multigroup', 'meetup', 'Tech Istanbul | Şişhane', 'Beyoğlu / İstanbul', 0, 1782572400, 1782583200, 'https://gathin.com/events/jetpack-compose-accessibility-community-networking-100', 'gathin', 'published', 1, '', 0),
  ('gathin-73647959493745060198', 'multigroup-skyward-2026', 'MultiGroup Skyward 2026', 'MultiGroup Community 6 Yaşında, gelin birlikte kutlayalım Uzun ve emek dolu bir yolculuğun daha önemli bir kilometre taşını geride bırakıyoruz. Ve bunu her…', '<p><strong>MultiGroup Community 6 Yaşında, gelin birlikte kutlayalım 🥂</strong><br><br>Uzun ve emek dolu bir yolculuğun daha önemli bir kilometre taşını geride bırakıyoruz. Ve bunu her zaman yaptığımız en iyi şekilde, bir araya gelerek kutluyoruz.<br><br>Bu süreçte bizimle birlikte gelişen, katkı sunan; ekip üyelerimize, mentorlarımıza, konuşmacılarımıza ve en önemlisi siz değerli katılımcılarımıza teşekkür etmek için sizi özel bir kutlamaya davet ediyoruz.<br><br><strong>☀️ </strong><strong><em>“Bu sıcakta etkinlik mi olur?” diyorsun, haklısın.</em></strong><em><br></em><br>Evet, havalar ısındı ve uzun oturumlara girmek bu dönemde zor olabilir. Ama bu etkinlik bir konferans değil.<br>Bu bir kutlama. <em>Hiçbir oturum yok, sahne yok, sunum yok. </em>Sadece bir araya geldiğimiz, sohbet ettiğimiz, güzel vakit geçirdiğimiz ve ikramların eşlik ettiği keyifli bir gün olacak.<br><br><strong><em>🥂 Peki ne yapmalısın?</em></strong><br><br>Etkinliğimiz her zamanki gibi tamamen ücretsizdir. Ancak biliyorsun ki toplulukları ayakta tutmak, geliştirmek ve büyütmek ciddi bir emek ve destek gerektiriyor. Eğer bu yolculuğa katkı sağlamak istersen, Community Supporter Ticket alarak bize destek olabilirsin.</p>', 'https://files-01.apiollon.com/download.php?file=6a2c060e8d7246.22088456.jpg&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multigroup', 'meetup', 'Gazeteci Ümit Deniz Sokağı No:11', 'Beşiktaş / İstanbul', 0, 1782658800, 1782673200, 'https://gathin.com/events/multigroup-skyward-2026-736', 'gathin', 'published', 0, '', 1),
  ('gathin-99761462817498966059', 'kotlin-deep-dive-aadc-2', 'Kotlin Deep Dive — AADC #2', 'Özellikle Kotlini sadece kullanmak değil, dilin sunduğu güçlü özellikleri derinlemesine anlamak isteyen geliştiriciler için hazırladığımız bu özel oturumda,…', '<p>Özellikle Kotlini sadece kullanmak değil, dilin sunduğu güçlü özellikleri derinlemesine anlamak isteyen geliştiriciler için hazırladığımız bu özel oturumda, Kotlinin modern uygulama geliştirmedeki en önemli yapı taşlarını birlikte keşfedeceğiz. Günlük projelerde sıkça kullanılan özelliklerin arkasındaki çalışma prensiplerini öğrenirken, daha okunabilir, güvenli ve performanslı kod yazmak için kullanılan ileri seviye Kotlin tekniklerini gerçek dünya senaryoları üzerinden inceleyeceğiz.<br><br>Kotlinin güçlü tip sistemi, fonksiyonel programlama yaklaşımı, eşzamanlı programlama araçları ve Kotlin Multiplatforma özel mekanizmaları hakkında kapsamlı bir bakış kazanmak isteyen geliştiriciler için bu oturumu kaçırmayın!<br><br>🎯 Kimler Katılmalı?<br><br>🔷 Kotlin bilgisini ileri seviyeye taşımak ve dilin güçlü özelliklerini daha etkin kullanmak isteyen Android Geliştiriciler.<br>🔷 Daha temiz, güvenli ve sürdürülebilir kod yazma pratikleri kazanmak isteyen Yazılım Mühendisleri.<br>🔷 Coroutine, Flow ve modern Kotlin araçlarını gerçek projelerde daha verimli kullanmak isteyen Mobil Geliştiriciler.<br>🔷 Kotlin Multiplatform (KMP) ekosistemine giriş yapmak veya mevcut bilgisini derinleştirmek isteyen geliştiriciler.<br><br>– MultiGroup ❤️ Wite</p>', 'https://files-01.apiollon.com/download.php?file=6a1f03f032e0d5.36744911.jpg&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multigroup', 'workshop', '', '', 1, 1781283600, 1781294400, 'https://gathin.com/events/kotlin-deep-dive-—-aadc-2-997', 'gathin', 'published', 0, '', 2),
  ('gathin-26330408148586574079', 'bosphorus-connect-sea-gathering', 'Bosphorus Connect — Sea Gathering', 'Yazın en özel günlerinden birinde, Boğaz’ın eşsiz atmosferinde gerçekleşen seçkin bir networking deneyimine davetlisin. Bosphorus Connect — Sea Gathering,…', '<p>Yazın en özel günlerinden birinde, Boğaz’ın eşsiz atmosferinde gerçekleşen seçkin bir networking deneyimine davetlisin.<br><br>Bosphorus Connect — Sea Gathering, alanında uzman özel konukları bir araya getirerek; yeni bağlantılar kurabileceğin, ilham alabileceğin ve kaliteli sohbetlerin içinde yer alabileceğin benzersiz bir buluşma sunuyor.<br>Güneşin Boğaz sularına yansıdığı bu keyifli yaz gününde; soğuk içecekler eşliğinde, şehrin en ikonik manzarasında ilerleyen bir tekne turunda bir araya geliyoruz.<br><br>Bu etkinlik sadece bir network buluşması değil — Boğaz’ın doğal akışı içinde, networkün kendiliğinden şekillendiği bir atmosfer.<br><br>Sınırlı kontenjan, seçkin katılımcılar ve unutulmaz bir Boğaz rotası seni bekliyor.</p>', 'https://files-01.apiollon.com/download.php?file=6a1ee4863c8040.46140537.jpg&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multigroup', 'meetup', 'Üsküdar Valide Sultan Gemisi iskelesi', 'Üsküdar / İstanbul', 0, 1783767600, 1783778400, 'https://gathin.com/events/bosphorus-connect-—-sea-gathering-263', 'gathin', 'published', 0, '', 3),
  ('gathin-58354913950294587850', 'architecture-design-patterns', 'Architecture & Design Patterns', 'Mobil uygulama geliştirme dünyasında sağlam, sürdürülebilir ve test edilebilir bir yapı kurmak, başarılı bir projenin en önemli temel taşıdır. Hazırladığımız…', '<p>Mobil uygulama geliştirme dünyasında sağlam, sürdürülebilir ve test edilebilir bir yapı kurmak, başarılı bir projenin en önemli temel taşıdır. Hazırladığımız bu özel oturumda, modern Android ve Kotlin Multiplatform (KMP) ekosistemindeki en güncel mimari yaklaşımları ve tasarım desenlerini derinlemesine inceliyoruz. Karmaşık iş mantıklarını nasıl daha sade hale getirebileceğinizi, uygulamanızı nasıl modüllere ayırarak ölçeklendirebileceğinizi ve hataları en zarif şekilde nasıl yöneteceğinizi öğrenmek için bu etkinliği kaçırmayın!<br><br><strong>🎯 Kimler Katılmalı?</strong><br><br>🔷 Mimari bilgisini derinleştirmek ve en iyi pratikleri (best practices) öğrenmek isteyen Android Geliştiriciler.<br>🔷 Büyük ölçekli projelerde modülerizasyon ve temiz mimari süreçlerini yöneten Yazılım Mühendisleri ve Mobil Mimarlar.<br>🔷 Kotlin Multiplatform (KMP) ile kod paylaşımı konseptine ilgi duyan Mobil Teknoloji Liderleri.<br><br>- <strong>MultiGroup ❤️ Wite</strong></p>', 'https://files-01.apiollon.com/download.php?file=6a059a3d6772f6.19653649.jpg&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multigroup', 'workshop', '', '', 1, 1778864400, 1778875200, 'https://gathin.com/events/architecture-design-patterns-583', 'gathin', 'published', 0, '', 4),
  ('gathin-17806203016586284320', 'multigroup-tech-summit-2026', 'MultiGroup Tech Summit 2026', 'MultiGroup Tech Summit Yaklaşıyor Günümüzde teknolojiyi ve yenilikleri takip etmek artık bir tercih değil, bir gereklilik. Ancak sürekli değişen ve hızla…', '<p><strong>MultiGroup Tech Summit Yaklaşıyor 🚀</strong><br><br>Günümüzde teknolojiyi ve yenilikleri takip etmek artık bir tercih değil, bir gereklilik. Ancak sürekli değişen ve hızla gelişen bu dünyada güncel kalmak her zaman kolay olmayabiliyor.<br><br>MultiGroup Tech Summit kapsamında, sektörün önde gelen şirketlerinden değerli konukları ağırlıyor; en güncel teknolojileri, trendleri ve gerçek deneyimleri doğrudan uzmanlarından dinleme fırsatı sunuyoruz. Sadece dinlemekle kalmayıp, birlikte tartışabileceğin, sorular sorabileceğin ve güçlü bağlantılar kurabileceğin bir ortam oluşturuyoruz.<br><br>Alan veya deneyim seviyen fark etmeksizin, teknolojide neler olup bittiğini yakından takip etmek ve bu dönüşümün bir parçası olmak istiyorsan, sen de aramıza katıl.<br><br><em>Gelin, geleceği birlikte keşfedelim. 🌍✨</em></p>', 'https://files-01.apiollon.com/download.php?file=69dced51459742.98077538.png&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multigroup', 'summit', 'Teknasyon HQ', 'Sarıyer / İstanbul', 0, 1778317200, 1778335200, 'https://gathin.com/events/multigroup-tech-summit-2026-178', 'gathin', 'published', 0, '', 5),
  ('gathin-97813864354681878416', 'bwai-program-build-a-gemini-powered-youtube-summarizer-demo', 'BWAI Program - Build a Gemini-Powered YouTube Summarizer (Demo)', 'Build with AI Programı’nın ilk oturumu olan “Build a Gemini-Powered YouTube Summarizer” etkinliğini, bu oturumları ilerleyen süreçte gerçekleştirecek…', '<p>Build with AI Programı’nın ilk oturumu olan <strong>“Build a Gemini-Powered YouTube Summarizer”</strong> etkinliğini, bu oturumları ilerleyen süreçte gerçekleştirecek organizatörlerimize özel bir demo oturumu olarak düzenliyoruz.<br><br>Bu demo oturumuna katılarak programın akışını, içerik yapısını ve uygulama sürecini yakından deneyimleyebilir, sürece aktif olarak dahil olabilirsiniz.<br><br><em>Not: Demo oturumu organizatörlere özel olarak planlandığı için, katılım linkinin üçüncü kişilerle paylaşılmamasını rica ederiz.</em></p>', 'https://files-01.apiollon.com/download.php?file=699c6b28a31b44.67725666.png&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multigroup', 'bootcamp', '', '', 1, 1771956000, 1771963200, 'https://gathin.com/events/bwai-program-build-a-geminipowered-youtube-summarizer-demo-978', 'gathin', 'published', 0, '', 6),
  ('gathin-64977629554876323476', 'build-with-ai-certification-program-2026', 'Build with AI Certification Program 2026', 'Build with AI Program 2026 Yaklaşıyor! Yapay zekâ dünyasına güçlü bir giriş yapmak, bilgisini derinleştirmek ve teoriyi pratiğe dönüştürmek isteyen herkes için…', '<p><strong>Build with AI Program 2026 Yaklaşıyor! 🚀</strong><br><br>Yapay zekâ dünyasına güçlü bir giriş yapmak, bilgisini derinleştirmek ve teoriyi pratiğe dönüştürmek isteyen herkes için özel olarak tasarladığımız Build with AI Program 2026, Google iş birliğiyle çok yakında başlıyor.<br><br>Bu kapsamlı program boyunca katılımcılar, yapay zekânın farklı alanlarına odaklanan toplam 12 workshop oturumuna katılma fırsatı elde edecek. İki aşamalı olarak kurgulanan bu seri 6 Orta Düzey ve 6 İleri Düzey workshop olmak üzere yapılandırıldı.<br><br>Katılımcılar program sonunda 2 farklı sertifika kazanma şansına sahip olacak. Ayrıca süreci başarıyla tamamlayıp belirli başarı kriterlerinin üzerine çıkan 50 katılımcı, özel olarak düzenlenecek mezuniyet ve kutlama etkinliğinde ağırlanacak.<br><br><em>Hazırsanız, yapay zekâ yolculuğunuzu birlikte inşa edelim.</em><br><br>- <strong>MultiGroup ❤️ Google</strong></p>', 'https://files-01.apiollon.com/download.php?file=698ef6efdfdbf5.63827127.png&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multigroup', 'bootcamp', '', '', 1, 1774890000, 1780246800, 'https://gathin.com/events/build-with-ai-program-2026-649', 'gathin', 'published', 0, '', 7),
  ('gathin-71746012821530826513', 'multigroup-ui-ux-gathering-2026', 'MultiGroup UI/UX Gathering 2026', 'MultiGroup UI/UX Gathering Geliyor! Tasarım dünyasına ilgi duyan yaratıcı zihinleri bir araya getirecek MultiGroup Design Meetup, çok yakında tasarım…', '🎨 MultiGroup UI/UX Gathering Geliyor!

Tasarım dünyasına ilgi duyan yaratıcı zihinleri bir araya getirecek MultiGroup Design Meetup, çok yakında tasarım severlerle buluşuyor!

MultiGroup tarafından organize edilen bu özel etkinlik; sahnede yer alacak deneyimli ürün tasarımcıları, UI/UX uzmanları ve topluluk içinden ilham veren isimlerle birlikte, katılımcı odaklı ve etkileşimi yüksek bir deneyim sunmak için hazırlandı.

🧑‍🎨 Unutma kontenjanımız sınırlı
🎯 UI / UX & Product Design Odaklı Konuşmalar
🤍 Topluluk Merkezli Samimi Network Alanı', 'https://files-01.apiollon.com/download.php?file=6970cb76ef7702.58620303.png&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multigroup', 'meetup', 'Tasarim Atolyesi Kadikoy', 'Kadıköy / İstanbul', 0, 1770454800, 1770472800, 'https://gathin.com/events/multigroup-design-gathering-2026-717', 'gathin', 'published', 0, '', 8),
  ('gathin-93146546978456602071', 'multigroup-developer-meetup-2026', 'MultiGroup Developer Meetup 2026', 'MultiGroup Developer Meetup Yaklaşıyor! Web ve mobil geliştirmeye ilgi duyan geliştiricilerin bir araya geleceği MultiGroup Developer Meetup, çok yakında…', '📢 MultiGroup Developer Meetup Yaklaşıyor!

Web ve mobil geliştirmeye ilgi duyan geliştiricilerin bir araya geleceği MultiGroup Developer Meetup, çok yakında sizlerle!

MultiGroup tarafından düzenlenen bu özel buluşma; sahnede yer alacak deneyimli web ve mobil geliştiriciler, topluluk içinden güçlü isimler ve samimi atmosferiyle katılımcılara odaklı, verimli ve etkileşimli bir etkinlik deneyimi sunmak için hazırlanıyor.

💻 100 Kişilik Sınırlı Kontenjan
😎 Web & Mobil Odaklı Konuşmacılar
🤝 Topluluk Temelli Network Deneyimi', 'https://files-01.apiollon.com/download.php?file=693fe30d537916.64204006.png&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multigroup', 'meetup', 'adesso Maslak Ofis', 'Sarıyer / İstanbul', 0, 1768035600, 1768057200, 'https://gathin.com/events/multigroup-developer-meetup-2026-931', 'gathin', 'published', 0, '', 9),
  ('gathin-48336981211368838149', 'mobile-dev-summit-2026-modesum26', 'Mobile Dev Summit 2026 #modesum26', 'Mobile Developer Summit 2026 Yaklaşıyor! Mobil geliştiriciliğe ilgi duyanların her yıl heyecanla beklediği buluşma Mobile Developer Summit 2026, çok yakında…', '<p>📢 Mobile Developer Summit 2026 Yaklaşıyor!<br><br>Mobil geliştiriciliğe ilgi duyanların her yıl heyecanla beklediği buluşma Mobile Developer Summit 2026, çok yakında yeniden karşınızda! MultiGroup tarafından düzenlenen bu büyük yazılım zirvesi; ilham veren konuşmacıları, özel konukları ve güçlü sponsorlarıyla katılımcılara dolu dolu, verimli bir hafta sonu sunmak için hazırlanıyor.<br><br>💻 500+ Değerli Katılımcı<br>😎 30+ Alanında Uzman Konuşmacı<br>🎯 15+ Önde Gelen Şirket<br><br>👀 Not: Community Supporter Ticket alarak etkinliğin gelişimine katkıda bulunabilirsin.</p>', 'https://files-01.apiollon.com/download.php?file=69c29304d36b43.93521848.png&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multigroup', 'summit', 'Haliç Üniversitesi', 'İstanbul', 0, 1775293200, 1775314800, 'https://gathin.com/events/mobile-developer-conference-2026-483', 'gathin', 'published', 0, '', 10),
  ('gathin-30356925359298502841', 'mobile-developer-summit-2025', 'Mobile Developer Summit 2025', 'Mobile Developer Summit 2025 Yaklaşıyor! Mobil dünyaya yön veren geliştiricilerin yıllık buluşması Mobile Developer Summit, geri dönüyor! MultiGroup tarafından…', '📢 Mobile Developer Summit 2025 Yaklaşıyor!

Mobil dünyaya yön veren geliştiricilerin yıllık buluşması Mobile Developer Summit, geri dönüyor!

MultiGroup tarafından düzenlenen bu büyük yazılım zirvesi, sektörün önde gelen şirketleri, geliştirici ekipleri ve alanında uzman konuşmacılarıyla dolu verimli bir hafta sonu için seni bekliyor.

💻 200+ Katılımcı 😎 30+ Uzman Konuşmacı 🏢 20+ Şirket ve Geliştirici Ekip

Etkinlik Organizatörleri: Serkan Alç', 'https://files-01.apiollon.com/download.php?file=690469ab3d98a0.76886049.png&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multigroup', 'summit', 'Trendyol Campus', 'İstanbul', 0, 1765616400, 1765638000, 'https://gathin.com/events/mobile-developer-summit-2025-303', 'gathin', 'published', 0, '', 11),
  ('gathin-00862251114890812610', 'data-science-conference-2025', 'Data Science Conference 2025', 'Data Science Conference 25 Yaklaşıyor! Veri bilimine ilgi duyanların yıllık buluşması Data Science Conference, yeniden sahnede! MultiGroup tarafından…', '📢 Data Science Conference 25 Yaklaşıyor!

Veri bilimine ilgi duyanların yıllık buluşması Data Science Conference, yeniden sahnede!

MultiGroup tarafından düzenlenen bu büyük teknoloji zirvesi, alanında uzman konuşmacıları, özel konukları ve değerli sponsorlarıyla size ilham dolu bir gün yaşatmak için hazırlanıyor.

💻 300+ Katılımcı 😎 30+ Uzman Konuşmacı 🎯 10+ Şirket Katılımı

Etkinlik Organizatörleri: Serkan Alç, Göker Güner, Enes Fehmi Manan', 'https://files-01.apiollon.com/download.php?file=68fa87dc7ff9e4.70870599.png&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multigroup', 'conference', 'Haliç Üniversitesi', 'İstanbul', 0, 1763802000, 1763823600, 'https://gathin.com/events/data-science-conference-2025-008', 'gathin', 'published', 0, '', 12),
  ('gathin-62944986376529159230', 'web-developer-conference-2025', 'Web Developer Conference 2025', 'Web Developer Conference 25 Yaklaşıyor! Web geliştiriciliğe ilgi duyanların yıllık buluşması Web Developer Conference hızla yaklaşıyor! MultiGroup tarafından…', '📢 Web Developer Conference 25 Yaklaşıyor!

Web geliştiriciliğe ilgi duyanların yıllık buluşması Web Developer Conference hızla yaklaşıyor! MultiGroup tarafından düzenlenen bu büyük yazılım zirvesi, önde gelen konuşmacıları, özel konukları ve değerli sponsorlarıyla size verimli bir hafta sonu sunmak için hazırlanıyor.

💻 500+ Değerli Katılımcı 😎 30+ Alanında Uzman Konuşmacı 🎯 15+ Önde Gelen Şirket

👥 Etkinlik Organizatörleri: Serkan Alç, Elif Çağıl, Furkan Ünsalan', 'https://files-01.apiollon.com/download.php?file=68bd9534a5f036.53276367.png&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multigroup', 'conference', 'Kadir Has Üniversitesi', 'İstanbul', 0, 1758963600, 1758985200, 'https://gathin.com/events/web-developer-conference-629', 'gathin', 'published', 0, '', 13),
  ('gathin-96882134119504469163', 'data-science-summit-2025', 'Data Science Summit 2025', 'Data Science Summit 2025 Yaklaşıyor! Tüm veri bilimi meraklılarına sesleniyoruz! Yılın en ilham verici ve öğretici veri bilimi etkinliği için geri sayım…', 'Data Science Summit 2025 Yaklaşıyor!

📢 Tüm veri bilimi meraklılarına sesleniyoruz! Yılın en ilham verici ve öğretici veri bilimi etkinliği için geri sayım başladı.

🚀 Her yıl olduğu gibi bu yıl da topluluk olarak büyük bir heyecanla hazırlıklarımızı sürdürüyoruz. Veri biliminin nabzını tutan konuşmalar, sektörün öncüsü şirketlerle tanışma fırsatları ve dopdolu bir gün sizleri bekliyor!

İster deneyimli bir veri bilimci olun, ister bu alanda yolculuğuna yeni başlayan biri… Öğrenmek, ilham almak ve networkünüzü büyütmek için doğru yerdesiniz!', 'https://files-01.apiollon.com/download.php?file=689921418a0bb3.61916847.png&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multigroup', 'summit', 'KWORKS', 'İstanbul', 0, 1757152800, 1757167200, 'https://gathin.com/events/data-science-summit-25-968', 'gathin', 'published', 0, '', 14),
  ('gathin-55618251963157329461', 'advanced-android-from-code-to-production', 'Advanced Android: From Code to Production', 'Sıradan eğitimlerin ötesine geçen, seni gerçekten “ileri seviye” bir Android geliştirici gibi hissettirecek bir deneyime hazır ol. Bu program, yalnızca yeni…', '<p>Sıradan eğitimlerin ötesine geçen, seni gerçekten “ileri seviye” bir Android geliştirici gibi hissettirecek bir deneyime hazır ol. Bu program, yalnızca yeni şeyler öğretmeyi değil; bakış açını değiştirmeyi, geliştirme süreçlerine daha profesyonel ve stratejik yaklaşmanı hedefliyor.<br><br>Burada odak, tek tek konular değil; bir geliştiricinin nasıl düşündüğü, nasıl karar verdiği ve ortaya koyduğu işi nasıl bir üst seviyeye taşıdığı olacak. Gerçek dünyaya yakın bir perspektifle ilerleyerek, geliştirdiğin her şeyin daha sağlam, daha etkili ve daha “production-ready” olmasını sağlayacak bir mindset kazanacaksın.<br><br>Eğer hedefin sadece Android öğrenmek değil, bu alanda gerçekten ileri seviyeye çıkmaksa, doğru yerdesin.</p>', 'https://files-01.apiollon.com/download.php?file=69dffe30bb4850.76737623.png&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multiacademy', 'bootcamp', '', '', 1, 1778857200, 1784311200, 'https://gathin.com/events/advanced-android-from-code-to-production-556', 'gathin', 'published', 0, '', 15),
  ('gathin-92408168621499537800', 'practical-power-bi-for-data-analysis-certification-course', 'Practical Power BI for Data Analysis Certification Course', 'Veriyi sadece okumak değil, anlamlandırmak ve etkili içgörülere dönüştürmek ister misin? Practical Power BI for Data Analysis Certification Course, sıfırdan…', '<p>📌 Veriyi sadece okumak değil, anlamlandırmak ve etkili içgörülere dönüştürmek ister misin? Practical Power BI for Data Analysis Certification Course, sıfırdan başlayarak seni uygulamalı veri analizi süreçlerine hazırlayan, tamamen online ve proje odaklı kapsamlı bir sertifika programıdır.<br><br>Bu program, yalnızca Power BI kullanmayı öğretmekle kalmaz; veriyle düşünmeyi, doğru metrikleri belirlemeyi ve iş dünyasında kullanılan gerçek analiz senaryolarını çözmeyi de kazandırır.<br><br>📊 Power BI arayüzünü ve veri analizi mantığını temelden öğrenecek,<br>📈 Etkileyici ve profesyonel dashboard’lar tasarlayacak,<br>🧠 DAX, veri modelleme ve veri dönüşümü süreçlerini uygulamalı şekilde deneyimleyecek,<br>🔎 Ham veriyi anlamlı raporlara ve stratejik içgörülere dönüştürmeyi öğreneceksin.<br><br>✨ Practical Power BI for Data Analysis Certification Course ile veriyi değere dönüştürmeye başla.</p>', 'https://files-01.apiollon.com/download.php?file=69a8581364b9a5.81724167.png&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multiacademy', 'bootcamp', '', '', 1, 1775494800, 1777914000, 'https://gathin.com/events/practical-power-bi-for-data-analysis-certification-course-924', 'gathin', 'published', 0, '', 16),
  ('gathin-06533072219830292120', 'associate-fullstack-web-certification-course', 'Associate Fullstack Web Certification Course', 'Foundations of Fullstack Web Development Certification Program Modern web dünyasında hem frontend hem backend tarafında güçlü, gerçek sistemler geliştirebilen…', '🚀 Foundations of Fullstack Web Development Certification Program

Modern web dünyasında hem frontend hem backend tarafında güçlü, gerçek sistemler geliştirebilen bir fullstack developer olmaya hazır mısın?

Gerçek projelerle öğren, profesyonel seviyede uçtan uca web uygulamaları geliştirme yolunda güçlü bir adım at! Foundations of Fullstack Web Development Certification Program, modern teknolojilerle tasarlanmış, proje odaklı ve ücretli kapsamlı bir kariyer programıdır.

🎨 Frontend Development (React & Next.js)
⚙️ Backend Development (Go Ağırlıklı)
🔄 Fullstack Entegrasyon
🤖 Yapay Zekânın Sektördeki Yeri

📚 100 Saatlik Kaynak Eğitim Erişimi, 🧑‍💻 3 Ay Süren Canlı Eğitim Süreci (Toplam 80 Saat), 🧠 Özel Mentörlük & Danışmanlık Desteği.

Programı başarıyla tamamlayan katılımcılar, resmî sertifika almaya hak kazanır.

🌟 Şimdi kayıt ol ve uçtan uca sistemler geliştirmeye başla!', 'https://files-01.apiollon.com/download.php?file=697779ce0af7e8.95885433.png&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multiacademy', 'bootcamp', '', '', 1, 1785171600, 1790960400, 'https://gathin.com/events/associate-fullstack-web-certification-course-065', 'gathin', 'published', 0, '', 17),
  ('gathin-39991212930273913373', 'foundations-ui-ux-design-certification-course', 'Foundations UI/UX Design Certification Course', 'Foundations of UI/UX for Web Certification Course Web geliştiriciler için kullanıcı odaklı tasarım dünyasına giriş yap! Foundations of UI/UX for Web…', '🎨 Foundations of UI/UX for Web Certification Course

Web geliştiriciler için kullanıcı odaklı tasarım dünyasına giriş yap!

Foundations of UI/UX for Web Certification Course, tamamen ücretsiz, online ve uygulama odaklı bir eğitim programıdır. Bu kursta yalnızca tasarım teorisini değil, gerçek web projeleri üzerinden UI/UX süreçlerini adım adım uygulayarak öğrenirsin.

🧠 UI ve UX prensiplerini web perspektifiyle kavrayacak,
🎨 Figma ile modern, tutarlı ve ölçeklenebilir arayüzler tasarlayacak,
🧭 Kullanıcı akışları, wireframe ve prototipler ile deneyim odaklı düşünmeyi öğrenecek,
📱 Responsive tasarım yaklaşımıyla farklı ekranlar için çözümler üreteceksin.

Programı başarıyla tamamlayan katılımcılar, resmî sertifika almaya hak kazanır.

🌟 Şimdi kayıt ol ve UI/UX yolculuğunu başlat!', 'https://files-01.apiollon.com/download.php?file=6973893ec83941.15539748.png&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDQ1FWUURneWxaMGh1d3E5RQ', 'multiacademy', 'bootcamp', '', '', 1, 1779123600, 1782147600, 'https://gathin.com/events/foundations-ui-ux-design-certification-course-399', 'gathin', 'published', 0, '', 18),
  ('gathin-99241793086215583681', 'foundations-frontend-web-development-certification-course', 'Foundations Frontend Web Development Certification Course', 'Foundations of Web Development Certification Course React ile modern web geliştirme dünyasına adım at! Gerçek projelerle öğren, profesyonel web geliştirici…', '<p>🚀 Foundations of Web Development Certification Course<br><br>React ile modern web geliştirme dünyasına adım at!<br><br>Gerçek projelerle öğren, profesyonel web geliştirici olma yolunda ilk adımını at! Foundations of Web Development Certification Course, tamamen ücretsiz, online ve proje odaklı bir eğitim programıdır.<br><br>🌐 HTML, CSS ve JavaScript ile web’in temel yapı taşlarını kavrayacak,<br>⚛️ React ile etkileşimli ve dinamik kullanıcı arayüzleri geliştirecek,<br>🎨 UI/UX prensipleri ile kullanıcı deneyimi odaklı düşünmeyi öğrenecek,<br>🤖 Web geliştirmede yapay zekâ entegrasyonlarını keşfedeceksin.<br><br>Programı başarıyla tamamlayan katılımcılar, resmî sertifika almaya hak kazanacak.<br><br>🌟 Şimdi kayıt ol ve geleceğini kodlamaya başla!</p>', 'https://files-01.apiollon.com/download.php?file=69a857eb0bc7a3.82880931.png&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multiacademy', 'bootcamp', '', 'İstanbul', 1, 1773075600, 1777741200, 'https://gathin.com/events/foundations-of-web-development-certification-course--992', 'gathin', 'published', 0, '', 19),
  ('gathin-05614690565471726501', 'zero2end-ml-bootcamp-course', 'Zero2End ML Bootcamp Course', 'Zero2End ML Bootcamp Başlıyor! Makine öğrenimi alanına sıfırdan adım atmaya hazır mısın? Toplamda 40 saat sürecek bu ücretsiz Bootcamp ile veri bilimi ve…', '🚀 Zero2End ML Bootcamp Başlıyor!

Makine öğrenimi alanına sıfırdan adım atmaya hazır mısın? Toplamda 40 saat sürecek bu ücretsiz Bootcamp ile veri bilimi ve makine öğrenimi dünyasında güçlü bir temel atacak, sektör odaklı yetkinlikler kazanacaksın! 💡

🎥 Canlı Yayın + Kayıt Desteği: Tüm oturumlar canlı olarak yayınlanacak ve sonrasında tekrar izlenebilir olacak.

✨ 10’dan Fazla Uzman Konuşmacı Seni Bekliyor!
🤝 Toplulukla Birlikte Öğren!
📜 Sertifikalı Gelişim: Tüm oturumlara katılan ve proje aşamasını tamamlayan katılımcılara özel başarım sertifikası verilecektir.

🎟️ Oturumlar tamamen ücretsiz ve tüm katılımcılara açıktır.', 'https://files-01.apiollon.com/download.php?file=6908bdd6da1081.12012095.png&token=QWo4cW1TckxTTjBRb2lRZ1F4dG4zb2FhSHVUQXN0OmpkVFFDWGNOZkxSeHdpQ1FWUURneWxaMGh1d3E5RQ', 'multiacademy', 'bootcamp', '', '', 1, 1762102800, 1767114000, 'https://gathin.com/events/zero2end-ml-bootcamp-course-with-certification-056', 'gathin', 'published', 0, '', 20);
