// One-off: bake a monochrome Türkiye provinces SVG (public/turkey.svg) + export
// city label centroids (src/lib/turkey-map.ts) from the Highcharts tr-all source.
// Inputs are fetched to /tmp first (see the curl in the chat). Re-run only if the
// city set changes. Coordinate space matches the baked SVG's viewBox.
import fs from "node:fs";

const svg = fs.readFileSync("/tmp/turkey-keep.svg", "utf8");
const geo = JSON.parse(fs.readFileSync("/tmp/tr.geo.json", "utf8"));
const nameByHasc = {};
for (const f of geo.features) nameByHasc[f.properties.hasc] = f.properties.name;

const re = /id="(TR\.[A-Z0-9]+)"\s+d="([^"]+)"/g;
let m;
const provs = [];
let minX = 1e9, minY = 1e9, maxX = -1e9, maxY = -1e9;
const cen = {};
while ((m = re.exec(svg))) {
  const id = m[1];
  let d = m[2];
  const nums = (d.match(/-?\d+\.?\d*/g) || []).map(Number);
  let sx = 0, sy = 0, n = 0;
  for (let i = 0; i + 1 < nums.length; i += 2) {
    const x = nums[i], y = nums[i + 1];
    sx += x; sy += y; n++;
    if (x < minX) minX = x; if (x > maxX) maxX = x;
    if (y < minY) minY = y; if (y > maxY) maxY = y;
  }
  cen[id] = [Math.round((sx / n) * 10) / 10, Math.round((sy / n) * 10) / 10];
  d = d.replace(/-?\d+\.?\d*/g, (s) => String(Math.round(parseFloat(s) * 10) / 10));
  provs.push(`<path d="${d}"/>`);
}

const pad = 8;
const vbX = Math.floor(minX - pad), vbY = Math.floor(minY - pad);
const vbW = Math.ceil(maxX - minX + pad * 2), vbH = Math.ceil(maxY - minY + pad * 2);
const viewBox = `${vbX} ${vbY} ${vbW} ${vbH}`;
const out = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" fill="#141418" stroke="#34343b" stroke-width="0.6" stroke-linejoin="round">${provs.join("")}</svg>`;
fs.writeFileSync("public/turkey.svg", out);

const cityToHasc = {
  "İstanbul": "TR.IB", "Kocaeli": "TR.KC", "Tekirdağ": "TR.TG", "Kırklareli": "TR.KL",
  "Çanakkale": "TR.CK", "Bursa": "TR.BU", "Sakarya": "TR.SK", "Düzce": "TR.DU",
  "Zonguldak": "TR.ZO", "Ankara": "TR.AN", "İzmir": "TR.IZ", "Antalya": "TR.AL",
  "Kayseri": "TR.KY", "Hatay": "TR.HT",
};
const cityXY = {};
for (const [city, h] of Object.entries(cityToHasc)) cityXY[city] = cen[h];
const ts = `// generated by scripts/gen-turkey.mjs — Türkiye il merkezleri (public/turkey.svg uzayı)\nexport const TURKEY_VIEWBOX = ${JSON.stringify(viewBox)};\nexport const CITY_XY: Record<string, [number, number]> = ${JSON.stringify(cityXY)};\n`;
fs.writeFileSync("src/lib/turkey-map.ts", ts);
console.log("viewBox:", viewBox, "| public/turkey.svg:", fs.statSync("public/turkey.svg").size, "bytes");
console.log(cityXY);
