-- Recordings extracted from past-event videos + event↔recording links.
INSERT OR REPLACE INTO recordings (id,title,description,youtube_url,playlist_id,cover_image,category,video_count,sort_order,is_active) VALUES
  ('rec-k-4madpz','HR Break Series','','https://www.youtube.com/watch?v=hb3SABAVSn8','','events/hr-break-series-ff36df94.png','talk',0,2000,1),
  ('rec-k-1et6ghz','Google IO Extended Web Edition','','https://www.youtube.com/watch?v=A-WGqBjg9sA','','events/google-io-extended-web-edition-4c56483c.png','talk',0,2001,1),
  ('rec-k-ir233w','Online | Android 12 Bootcamp | Design for Everyone | Begüm Yolcu','','','PLZj2Q42tw-6_YwlaPydXHu41zXHV2OHSc','events/online-android-12-bootcamp-design-for-everyone-begum-yolcu-24c79c84.png','bootcamp',0,2002,1);
INSERT OR REPLACE INTO event_recordings (event_id,recording_id) VALUES
  ('ev-hr-break-series-ff36df94','rec-k-4madpz'),
  ('ev-google-io-extended-web-edition-4c56483c','rec-k-1et6ghz'),
  ('ev-online-android-12-bootcamp-design-for-everyone-begum-yolcu-24c79c84','rec-k-ir233w'),
  ('ev-online-android-12-bootcamp-styles-themes-material-design-caner-ture-aa25e1b6','rec-k-ir233w'),
  ('ev-online-android-12-bootcamp-jetpack-compose-basics-caner-ture-259ea769','rec-k-ir233w'),
  ('ev-online-android-12-bootcamp-repository-workmanager-begum-yolcu-70445965','rec-k-ir233w'),
  ('ev-online-android-12-bootcamp-filtering-detail-views-caner-ture-ae495c96','rec-k-ir233w'),
  ('ev-databases-recyclerview-coroutines-android-12-bootcamp-826c21e2','rec-k-ir233w'),
  ('ev-zero2end-course-with-certification-7358fba8','rec-zero2end-ml'),
  ('ev-data-science-summit-2025-336f257d','rec-data-summit-25'),
  ('ev-web-developer-summit-25-d7d891d6','rec-web-dev-conf-25'),
  ('ev-android-blast-off-jetpack-compose-bootcamp-18857d79','rec-android-blastoff'),
  ('ev-ios-developer-oluyorum-online-icerik-serisi-892cd7a2','rec-dev-oluyorum-ios'),
  ('ev-generativeai-fundamentals-with-gemini-64a8a503','rec-genai-gemini'),
  ('ev-datacommit-series-d244edf8','rec-datacommit'),
  ('ev-datacommit-series-ad0e9c93','rec-datacommit'),
  ('ev-hr-break-series-ff36df94','rec-hr-break'),
  ('ev-data-science-conference-dasa-conf-990a05ff','rec-data-conf-25'),
  ('ev-webfree23-web-developer-conference-0d5e9f62','rec-web-dev-conf-25'),
  ('ev-online-android-12-bootcamp-design-for-everyone-begum-yolcu-24c79c84','rec-android12'),
  ('ev-online-android-12-bootcamp-styles-themes-material-design-caner-ture-aa25e1b6','rec-android12'),
  ('ev-online-android-12-bootcamp-jetpack-compose-basics-caner-ture-259ea769','rec-android12'),
  ('ev-online-android-12-bootcamp-repository-workmanager-begum-yolcu-70445965','rec-android12'),
  ('ev-online-android-12-bootcamp-filtering-detail-views-caner-ture-ae495c96','rec-android12'),
  ('ev-online-android-12-bootcamp-get-display-data-caner-ture-0f4a288a','rec-android12'),
  ('ev-online-android-12-bootcamp-recyclerview-caner-ture-4937152e','rec-android12'),
  ('ev-databases-recyclerview-coroutines-android-12-bootcamp-826c21e2','rec-android12'),
  ('ev-databases-recyclerview-room-android-12-bootcamp-62ab5bcf','rec-android12');
